package: statistics
version: 3.1.0-dev-29-11-19
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/statistics

page:
    title: "translate:statistics_stats"
    icon: rex-icon fa-line-chart
    perm: statistics[]
    subpages:
        stats:
            title: "translate:statistics_stats"
            icon: rex-icon fa-pie-chart
        pages:
            title: "translate:statistics_pages"
            icon: rex-icon fa-file-text-o
        articles:
            title: "Artikel-Statistiken"
            icon: rex-icon fa-file-text-o
        referer:
            title: "translate:statistics_referer"
            icon: rex-icon fa-external-link
        media:
            title: "translate:statistics_media"
            icon: rex-icon fa-image
        events:
            icon: rex-icon fa-bullhorn
            title: "translate:statistics_api_events"
        settings:
            title: "translate:statistics_settings"
            perm: statistics[settings]
            icon: rex-icon fa-cog
        help:
            {
                title: "translate:statistics_help",
                icon: rex-icon fa-info-circle,
                itemclass: pull-right,
            }

        

requires:
    redaxo: "^5.12"
    php:
        version: ">=7.4"

default_config:
    statistics_ignored_paths: ""
    statistics_ignored_ips: ""
    statistics_visit_duration: 30
    statistics_scroll_pagination: "none"
    statistics_ignore_url_params: false
    statistics_default_datefilter_range: "thisYear"
    statistics_combine_all_domains: true
    statistics_show_chart_toolbox: false
    statistics_ignore_backend_loggedin: true
    statistics_rec_onlyok: false

    statistics_media_log_all: false
    statistics_media_log_mm: true

    statistics_api_enable: false



installer_ignore:
    - .git
    - preview
    - .tools
